---
title: "Health and Financial Impact of Severe-Weather Events Between 2005 and 2011"
---

## Synopsis

## Data Processing

R libraries _data.table_ and _dplyr_ are used for data manipulation, _lubridate_ for handling dates, and _ggplot2_ for plotting.

```{r }
library(data.table)
library(ggplot2)
library(dplyr)
library(lubridate)
```

We begin by setting hard-coded parameters for this analysis, most importantly the URL for raw data. The remaining convenience parameters organize analysis files.

```{r }
# Data subdirectory.
dat_dir <- "data"
# Raw data subdirectory.
raw_dir <- file.path(dat_dir, "raw")
# Intermediate data subdirectory.
int_dir <- file.path(dat_dir, "intermediate")
# Clean data subdirectory.
cln_dir <- file.path(dat_dir, "processed")

# Raw-data URL.
raw_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
# Raw-data filename.
raw_fnm <- "StormData.csv.bz2"
# Raw-data path.
raw_pth <- file.path(raw_dir, raw_fnm)

# Cached data.
cch_fnm <- "StormData.csv"
cch_pth <- file.path(int_dir, cch_fnm)
```


## Results

```{r , eval=F, include=F, results="hide"}
library(rmarkdown)
rmarkdown::render(
    "code/severe-weather-writeup_180630-1512.Rmd",
    output_dir = "text",
    clean = T
)
```
